server:
  port: 8085

## URL Rest Services applicacion
coins:
  baseURL: 'api/coins'
  healthAPI: '/health-api'
  listCategories: '/categories/list'

## Url Coin Gecko RestService
api:
  urlCoinGecko: 'https://api.coingecko.com/api/v3'
  ping: '/ping'
  listCategories: '/coins/categories/list'
